CREATE TABLE user_login (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(400) not null,
  mail varchar(400) not null unique, --mail unico obligatiro
  password varchar(500) not null,
  asset boolean default false, --pordefecto inactivo para activar el correo
  state int default 1, --por defecto Activo
  created_id int,
  created_user varchar(300),
  created_date timestamptz,
  updated_id int,
  updated_user varchar(300),
  updated_date timestamptz,
  verified_date timestamptz
);