<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MsUser.Api\MsUser.Api.csproj" />
    <ProjectReference Include="..\MsUser.Application\MsUser.Application.csproj" />
    <ProjectReference Include="..\MsUser.Domain\MsUser.Domain.csproj" />
    <ProjectReference Include="..\MsUser.Persistence\MsUser.Persistence.csproj" />
    <ProjectReference Include="..\MsUser.Service\MsUser.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
