<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    <PackageReference Include="RealPlaza.Core" Version="1.1.10" />
    <PackageReference Include="RealPlaza.Web" Version="1.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="WolverineFx" Version="5.9.2" />
    <PackageReference Include="WolverineFx.FluentValidation" Version="5.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MsUser.Application\MsUser.Application.csproj" />
    <ProjectReference Include="..\MsUser.Database\MsUser.Database.csproj" />
    <ProjectReference Include="..\MsUser.Internal.Contract\MsUser.Internal.Contract.csproj" />
    <ProjectReference Include="..\MsUser.Service\MsUser.Service.csproj" />
  </ItemGroup>

</Project>
